version: '3'
services:
    donation-alert:
        container_name: donation-alert
        image: node:18-alpine
        working_dir: /app
        command: >
            sh -c "apk add --no-cache python3 make g++ &&
                npm install &&
                node server.js"
        ports:
            - "2005:3000"
        volumes:
            - /media/devmon/sda2-ata-ST500VT000-1DK14/Hosting/obs:/app
        restart: unless-stopped
        logging:
            driver: json-file
            options:
                max-size: "10m"
                max-file: "5"
        deploy:
            resources:
                limits:
                    memory: "2030043136"
        cpu_shares: 90
        hostname: donation-alert
        networks:
            - obs_default

networks:
    obs_default:
        name: obs_default
